version: "2.1"

services:
  infinitude:
    container_name: infinitude
    hostname: infinitude
    image: nebulous/infinitude
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - "3000:3000"
    environment:
      - APP_SECRET=Pogotudinal
      - PASS_REQS=1020
      - MODE=Production
#      - SERIAL_TTY=/dev/ttyUSB0
#      - SERIAL_SOCKET=10.0.0.1:1234
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
